Groups/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='Group'

urlpatterns =[
    path('',views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='CreateGroup'),
    path('post/in/<int:pk2>/',views.SingleGroup.as_view(), name='SingleGroup'),
    path('join',views.JoinGroup.as_view(), name='JoinGroup'),
    path('leave',views.LeaveGroup.as_view(), name='LeaveGroup')

]

Posts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='Posts'

urlpatterns = [

    path('',views.PostList.as_view(), name='all'),
    # path('new/', views.CreatePost.as_view(), name='create'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/',views.UsrPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name ='for_user'),
    path('delete/<int:pk>/',views.DeletePost.as_view(), name='delete'),
]

simple_social/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name ='home'),
    path('account/',include('account.urls', namespace='accounts')),
    path('account/',include('django.contrib.auth.urls')),
    path('test/',views.Testpage.as_view(), name="test"),
    path('thanks/',views.Thankspage.as_view(), name="thanks"),
    path('group/',include('Groups.urls', namespace='Groups')),
    path('post/',include('Posts.urls', namespace='Posts')),

]

Groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.
#import misaka
from django.contrib.auth import get_user_model
user = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=200, blank=False)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    #description_html = models.TextField(editable=False, default='',blank=True)
    members = models.ManyToManyField(user, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        #self.description_html = misaka.html(self.description)
        super().save(*args,**kwargs)
    
    def get_absolute_url(self):
        return reverse('Group:SingleGroup',)

    class Meta:
        ordering= ['name']


class GroupMember(models.Model):
    Group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(user, related_name='user_groups', on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.user.username


    class Meta:
        unique_together = ('Group','user')

Groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import(LoginRequiredMixin,PermissionRequiredMixin)
from django.urls import reverse
from django.views import generic  
from django.contrib import messages  
from . import models 
from django.shortcuts import get_object_or_404
from django.db import IntegrityError
# from django.views.generic import ListView, DetailView, CreateView
# Create your views here.


class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields =('name', 'description')
    model = models.Group

    def form_invalid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class SingleGroup(generic.DetailView):
    model = models.Group

   

    


class ListGroups(generic.ListView):
    model = models.Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):

    def get_redirect_url(self,*args,**kwargs):
        return reverse('Group:SingleGroup', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args,**kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))
        
        try:
            GroupMember.object.create(user = self.request.user, group=group)

        except IntegrityError:
            messages.warning(self.request,('warning aleady member!'))
        else:
            messages.success(self.request,'You are now member!')
        
        return super().get(request,*args,**kwargs)


class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('Group:SingleGroup', kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):
        
        try:
            membership = Group.GroupMember.object.filter(
                user = self.request.user,
                Group_slug = self.kwargs.get('slug')
            ).get()

        except Group.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are ot in this group')
        
        else:
            membership.delete()
            messages.success(self.request,'You have left the group!')

        return super().get(request,*args,**kwargs)

Groups/templates/Groups/group_base.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="row">

        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>

</div>

{% endblock %}

Groups/templates/Groups/group_detail.html
{% extends "Groups/group_base.html" %}

{% block pregroup %}
<h1>{{group.name}}</h1>
<h2>Member Count: {{group.members.count}}</h2>

<div class="containt">
    {% if user in group.members.all %}
        <a href="{% url 'Groups:LeaveGroup' slug=Group.slug %}">class='btn btn-lg btn-warning'>
            <span class="glyphicon glyphicon-remove-circle"></span>Leave</a>
    {% else %}
    <a href="{% url 'Groups:JoinGroup' slug=Group.slug %}">class='btn btn-lg btn-warning'>
        <span class="glyphicon glyphicon-ok-circle"></span>Join</a>
    {% endif %}    

</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    {% if group.posts.count == 0 %}
        <h2>No Post in this group yet!!</h2>
    {% else %}
        {% for post in group.posts.all %}
        {% include 'posts/_post.html' %}
        {% endfor %}
    {% endif %}

</div>

{% endblock %}

Groups/templates/Groups/group_form.html
{% extends "Groups/group_base.html" %}
{% load bootstrap3 %}
{% block group_content %}
<h4>Create a new group!!</h4>
<form action="{% url 'Group:CreateGroup' %}" id = 'group_form' method ='POST'>
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create Group">  
</form>
{% endblock%}

Groups/templates/Groups/group_list.html
{% extends "Groups/group_base.html" %}
{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back!!
            <a href="{% url 'Posts:for_user' username=user.username %}">
                @{{user.username}}
            </a>
        </h2>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to group page</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'Groups:CreateGroup' %}" class="btn btn-md btn-fill btn-warning btn-large"></a>
    <span class="glyphicon glyphicon-plus-sign">Create New Group!
    </span>
    {% endif %}
</div>

{% endblock %}

{% block group_content %}
<div class="coi-md-8"> 
    <div class="list-group">
        {% for group in objct_list %}
        <a class = "list-group-item" href="{% url 'Groups:SingleGroup' %}">
            <h3 class="title list-group-item-heading">{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">
                {{group.description_html|safe}}
                <div class="row">
                    <div class="col-md-4">
                        <span class="badge">{{group.members.count}}</span>
                        member{{group.member.count|pluralize}}
                    </div>
                    <div class="col-md-4">
                        <span class="badge">{{group.posts.count}}</span>
                        post{{group.post.count|pluralize}}
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}