Groups/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='Group'

urlpatterns =[
    path('',views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='CreateGroup'),
    path('post/in/<int:pk2>/',views.SingleGroup.as_view(), name='SingleGroup'),
    path('join',views.JoinGroup.as_view(), name='JoinGroup'),
    path('leave',views.LeaveGroup.as_view(), name='LeaveGroup')

]

Posts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='Posts'

urlpatterns = [

    path('',views.PostList.as_view(), name='all'),
    # path('new/', views.CreatePost.as_view(), name='create'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/',views.UsrPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name ='for_user'),
    path('delete/<int:pk>/',views.DeletePost.as_view(), name='delete'),
]

account/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views
# from django.contrib.auth.views.LoginView
# from django.contrib.auth.views.LogoutView

app_name = 'account'

urlpatterns = [ 
    path('', auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html'),name='login'),
    # default Logout
    # path('logout',  auth_views.LogoutView.as_view(), name ='logout'),
    path('logout',  auth_views.LogoutView.as_view(template_name='account/logout.html'), name ='logout'),
    path('signup/', views.SignUp.as_view(template_name='account/signup.html'),name='signup'),
]

simple_social/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name ='home'),
    path('account/',include('account.urls', namespace='accounts')),
    path('account/',include('django.contrib.auth.urls')),
    path('test/',views.Testpage.as_view(), name="test"),
    path('thanks/',views.Thankspage.as_view(), name="thanks"),
    path('group/',include('Groups.urls', namespace='Groups')),
    path('post/',include('Posts.urls', namespace='Posts')),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Star Social</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <!-- <link rel="stylesheet" href="{% static 'simplesocial/css/master.css'% }"> -->

</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark" role="navigation" id="navbar"> 
    <div class="container">
      <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>
      <ul class="nav navbar-nav navbar-right">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        {% if user.is_authenticated %}
          <!-- <li><a href="#">Post</a></li>
          <li><a href="#">Group</a></li>
          <li><a href="#">Create Group</a></li>
          <li><a href="{% url 'account:logout' %}">Log Out</a></li>  -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Posts:create' %}">Post <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Group:all' %}">Group <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'Group:CreateGroup' %}">Create Group</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:logout' %}">Log Out</a>
          </li>

        {% else %}
          <!-- <li><a href="#">Group</a></li>
          <li><a href="{% url 'account:login' %}">Log Out</a></li>
          <li><a href="{% url 'account:signup' %}">Sign Up</a></li> -->
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'Group:all' %}">Group <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:login' %}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'account:signup' %}">Sign Up</a>
          </li>

        {% endif %}
      </ul>
    </div>
  </nav>
 <div class="container mycontent">
  {% block content %}
  {% endblock %}
  
 </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome to star Social!</h1>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are logged In!</h1>

{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thank you visiting, come soon!</h1>

{% endblock %}