Groups/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='Group'

urlpatterns =[
    path('',views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='CreateGroup'),
    path('post/in/<int:pk2>/',views.SingleGroup.as_view(), name='SingleGroup'),
    path('join',views.JoinGroup.as_view(), name='JoinGroup'),
    path('leave',views.LeaveGroup.as_view(), name='LeaveGroup')

]

Posts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name='Posts'

urlpatterns = [

    path('',views.PostList.as_view(), name='all'),
    # path('new/', views.CreatePost.as_view(), name='create'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/',views.UsrPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/',views.PostDetail.as_view(),name ='for_user'),
    path('delete/<int:pk>/',views.DeletePost.as_view(), name='delete'),
]

simple_social/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name ='home'),
    path('account/',include('account.urls', namespace='accounts')),
    path('account/',include('django.contrib.auth.urls')),
    path('test/',views.Testpage.as_view(), name="test"),
    path('thanks/',views.Thankspage.as_view(), name="thanks"),
    path('group/',include('Groups.urls', namespace='Groups')),
    path('post/',include('Posts.urls', namespace='Posts')),

]

Posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import datetime
# from django.utils.text import slugify
# Create your models here.
#import misaka
from Groups.models import Group
from django.contrib.auth import get_user_model
user = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(user, related_name="posts", on_delete=models.CASCADE)
    created_at = models.DateTimeField(datetime.datetime.now())
    message = models.TextField(max_length=100)
    group = models.ForeignKey(Group, related_name="posts", on_delete = models.CASCADE, null = True, blank= True)


    def __str__(self):
        return self.message

    # def save(self, *args,**kwargs):
        #     se

    def get_absolute_url(self):
        return reverse('posts:single',kwargs={'username':self.user.username,'pk':self.pk})

    
    class Meta:
        ordering = ['-created_at']
        unique_together =['user','message']

Posts/views.py
from django.shortcuts import render
# from django.contrib.auth.models import User
#from django.core.urls import reverse_lazy
from django.urls import reverse_lazy
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.views import generic
from braces.views import SelectRelatedMixin
from . import models
from . import forms
from django.contrib import messages
from django.views.generic.edit import CreateView
from django.contrib.auth import get_user_model
user = get_user_model

# Create your views here.
 
class PostList(SelectRelatedMixin,generic.ListView):
    models = models.Post
    select_related = ('user','Group')


class UsrPosts(generic.ListView):
    models = models.Post
    template_name ='posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = user.objects.prefetch_related('post').get(username__iexact = self.kwargs.getme)
            
        except user.DoesNotExist:
            raise Http404
        
        else:
            return self.post_user.posts.all()


        def get_context_data(self,**kwargs):
            context = super().get_context_data(**kwargs)
            context['post_user'] = self.post_user
            return context


class PostDetail(SelectRelatedMixin,generic.DetailView):
    models = models.Post
    select_related=('user','group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(use_username__iexact = self.kwargs.get('username'))


class CreatePost(LoginRequiredMixin,SelectRelatedMixin,generic.CreateView):
    fields =('message','group')
    models = models.Post
    
    def form_invalid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin,SelectRelatedMixin,generic.DeleteView):
    models = models.Post
    select_related = ('user','Group')
    success_url = reverse_lazy('Post:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request,'Post Deleted')
        return super().delete(*args,**kwargs)

Posts/templates/posts/_post.html
<div class="post media">
<h3>
 {{post.message_html|safe}}
</h3>
<div class="media-body">
    <!-- <strong>{{post.user.username}}</strong> -->
    <h5 class="media-heading">
    <span class="username">
        <a href="{% url 'Posts:for_user' username=post.user.username %}">@{{post.user.username}}</a>
    </span>
    <time class="time">
        <a href="{% url 'Posts:SingleGroup' username=post.user.username pk=post.pk %}">{{post.created_at}}</a>
    </time>
</h5>
<div class="media-footer">
    {% if user.is_authenticated and post.user == user %}
    <a href="{% url 'Post:delete pk=post.pk' %}" title="delete" class="btn btn-simple"></a>
    <span class="glyphicon glyphicon-remove text-danger" aria-hidden="true"></span>
    <span class="text-danger icon-label">Delete</span>

</div>
</div>

</div>

Posts/templates/posts/post_confirm_delete.html
{% extends "Posts/post_base.html" %}
{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>
<div class="posts">
    {% include "Posts:/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
    <a href="{% url 'Posts:SingleGroup' username=user.username pk=object.pk %}" class="btn btn-simple btn-large btn-default">Cancel</a>
{% endblock %}

Posts/templates/posts/post_details.html
{% extends "Posts/post_base.html" %}
{% block post_content %}
<div class="col-md-8">
    {% include "Posts/_post.html"%}
</div>

{% endblock %}

Posts/templates/posts/post_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block post_content %}
<h4>Create a new Post</h4>
<form action="{url 'Post:create} " id='postForm' method="POST">
    {% csrf_token %}
    {% boottrap_form form %}
    <input type="submit" value="Post", class="btn btn-primary">
</form>


{% endblock %}

Posts/templates/posts/post_list.html
{% extends "Post/post_base.html" %}
{% load bootstrap3 %}

{% block pre_post_content %}
<div class="col-md-4">
    {% if request.user.is_authenticated %}
    <div class="card card-with-shadow">
        <div class ="content">
            <h5 class="title">Your Groups</h5>
            <ul class="list-unstyled">
                {% for member_group in get_user_group %}
                <li class="group-li-with-bullet">
                    <a href="{% url 'Group:SingleGroup' slug= member_group.group.slug %}"></a>
                </li>
                {% endfor %}
            </ul>
        </div>
 </div>
 {% endif %}
<div class="card card-with-shadow">
    <div class="content">
        <h5 class="title">All Groups</h5>
        <ul class="list-unstyled"></ul>
        {% for other_group in get_other_groups %}
        <li class="group-li-with-bullet"><a href="{% url 'Groups:SingleGroup' slug =other_group.slug %}"></a></li>

    </div>

</div>
</div>

{% endblock %}
{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
    {% include 'post/_post.html' %}
    {% endfor %}
    
</div>
{% endfor %}

Posts/templates/posts/posts_base.html
{% extends "base.html" %}
{% block content %}
<div class="post-page">
    <div class="container">
    <div class="row">

        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>

</div>

{% endblock %}

Posts/templates/posts/user_post_list.html
{% extends "Posts/post_base.html" %}
{% block prepost %}
<div class="col-md-4">
    <h1>@{{post_user.username}}</h1>
</div>
{% endblock %}

{% block post_content %}
<div class="col-md-8">
    {% for post in post_list %}
    {% include "Post/_post.html" %}
    {% endfor %}
</div>